apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cloud-centos-bootc-layered
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloud-centos-bootc-layered
    app.kubernetes.io/part-of: centos-bootc-layered
  name: cloud-centos-bootc-layered
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloud-centos-bootc-layered
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cloud-centos-bootc-layered
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc-layered/cloud-centos-bootc-layered@sha256:0791a2fedf51b3a65b714e445808bb87f5f83e92667d35bbfd68716ca9475ca8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
