apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cloud-centos-bootc-layered
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloud-centos-bootc-layered
    app.kubernetes.io/part-of: centos-bootc-layered
  name: cloud-centos-bootc-layered
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: cloud-centos-bootc-layered
status:
  loadBalancer: {}
