apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cloud-centos-bootc-layered
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc-layered/cloud-centos-bootc-layered@sha256:572933588cf474a9ce955152990a628b704a02c4602dc9c70842cee914792e3f
        name: container-image
        resources: {}
status: {}
