apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cloud-centos-bootc-layered
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloud-centos-bootc-layered
    app.kubernetes.io/part-of: centos-bootc-layered
  name: cloud-centos-bootc-layere3hbq
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cloud-centos-bootc-layered
    weight: 100
status: {}
